version: '3'
services:
  strapi:
    container_name: strapi
    build: .
    image: node:16-alpine
    restart: unless-stopped
    volumes:
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
    ports:
      - '1337:1337'
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
